blog:
  site: chaopeng.me
  path: /blog
  author: ChaoPeng
  blogname: 巢鹏的Pensieve
  inputpath: /Users/chaopeng/Documents/blog/to-be-publish
  outputpath: /Users/chaopeng/Documents/blog/chaopeng.github.com

author:
  mail: chaojianpeng@gmail.com
  gravatar: chaopeng@chaopeng.me
  gravatarserver: https://secure.gravatar.com
  weibo: http://weibo.com/chaojianpeng
  github: https://github.com/chaopeng
  wechat: Xszl-ULEKx9UrQae95lM
  disqus: chaopeng-me
